### ISSUE TITLE
Issue with model inference on AWS Lambda

### ISSUE THREAD

**Issue by mattmcclean** [fastai/fastai2#153]
Am attempting to run the fastai2 library for model inference using [AWS Lambda](https://aws.amazon.com/lambda/). Am getting an error as  the AWS Lambda execution environment is missing `/dev/sh` so the python multiprocessing library does not work with AWS Lambda (see StackOverflow issue [here](https://stackoverflow.com/questions/34005930/multiprocessing-semlock-is-not-implemented-when-running-on-aws-lambda)). Is there someway to bypass the PyTorch Dataloader logic when doing inference with a single item in a batch in memory to avoid having to use the multiprocessing python lib ?

The stack trace error is the following:

```
[Errno 38] Function not implemented: OSError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 35, in lambda_handler
    pred_class,pred_idx,outputs = learn.predict(bytes)
  File "/mnt/test/fastai2/lib/python3.6/dist-packages/fastai2/learner.py", line 215, in predict
    inp,preds,_,dec_preds = self.get_preds(dl=dl, with_input=True, with_decoded=True)
  File "/mnt/test/fastai2/lib/python3.6/dist-packages/fastai2/learner.py", line 203, in get_preds
    self._do_epoch_validate(dl=dl)
  File "/mnt/test/fastai2/lib/python3.6/dist-packages/fastai2/learner.py", line 159, in _do_epoch_validate
    with torch.no_grad(): self.all_batches()
  File "/mnt/test/fastai2/lib/python3.6/dist-packages/fastai2/learner.py", line 127, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/mnt/test/fastai2/lib/python3.6/dist-packages/fastai2/data/load.py", line 97, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "/mnt/test/fastai2/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 647, in __init__
    self._worker_result_queue = multiprocessing_context.Queue()
  File "/var/lang/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/var/lang/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 38] Function not implemented

Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f7e684206a0>>
Traceback (most recent call last):
  File "/mnt/test/fastai2/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 926, in __del__
  File "/mnt/test/fastai2/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 882, in _shutdown_workers
  if not self._shutdown:
    AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_shutdown'
    
```
Running with fastai2 version`0.0.11` and Python `3.6` and PyTorch `1.3.1`

**Comment by sgugger** [comment]
It looks like an issue with PyTorch, not fastai. In general, setting `num_workers=0` to your dataloaders will avoid launching multiprocessing. You might need to use the new method: `dl = other_dl.new(num_workers=0)`.

**Comment by mattmcclean** [comment]
I resolved it by adding the following line:

`learn.dls.valid.fake_l.num_workers=0`
