### ISSUE TITLE
Unknown error when using script from imagenette leaderboard to load data

### ISSUE THREAD

**Issue by richardyy1188** [fastai/fastai2#220]
Code below is from [fastai2 train_imagenette.py 2020-01 + MaxBlurPool](fastai2 train_imagenette.py 2020-01 + MaxBlurPool) that is on the leaderboard 
```
from fastai2.vision.all import *
def get_dataloaders(size, woof, bs, sh=0., workers=None):
    if size<=224: path = URLs.IMAGEWOOF_320 if woof else URLs.IMAGENETTE_320
    else        : path = URLs.IMAGEWOOF     if woof else URLs.IMAGENETTE
    source = untar_data(path)
    if workers is None: workers = min(8, num_cpus())
    dblock = DataBlock(blocks=(ImageBlock, CategoryBlock),
                       splitter=GrandparentSplitter(valid_name='val'),
                       get_items=get_image_files, get_y=parent_label)
    item_tfms=[RandomResizedCrop(size, min_scale=0.35), FlipItem(0.5)]
    batch_tfms=RandomErasing(p=0.9, max_count=3, sh=sh) if sh else None
    return dblock.dataloaders(source, path=source, bs=bs, num_workers=workers,
                           item_tfms=item_tfms, batch_tfms=batch_tfms)

dls = get_dataloaders(128, True, 64)
for b in dls[0]: break
```
and get
```
RuntimeError                              Traceback (most recent call last)

<ipython-input-5-49f97bab423f> in <module>()
----> 1 for b in dls[0]: break

4 frames

/usr/local/lib/python3.6/dist-packages/fastai2/data/load.py in __iter__(self)
     95         self.randomize()
     96         self.before_iter()
---> 97         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
     98             if self.device is not None: b = to_device(b, self.device)
     99             yield self.after_batch(b)

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in _next_data(self)
    854             else:
    855                 del self._task_info[idx]
--> 856                 return self._process_data(data)
    857 
    858     def _try_put_index(self):

/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in _process_data(self, data)
    879         self._try_put_index()
    880         if isinstance(data, ExceptionWrapper):
--> 881             data.reraise()
    882         return data
    883 

/usr/local/lib/python3.6/dist-packages/torch/_utils.py in reraise(self)
    392             # (https://bugs.python.org/issue2651), so we work around it.
    393             msg = KeyErrorMessage(msg)
--> 394         raise self.exc_type(msg)

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data = next(self.dataset_iter)
  File "/usr/local/lib/python3.6/dist-packages/fastai2/data/load.py", line 106, in create_batches
    yield from map(self.do_batch, self.chunkify(res))
  File "/usr/local/lib/python3.6/dist-packages/fastai2/data/load.py", line 127, in do_batch
    def do_batch(self, b): return self.retain(self.create_batch(self.before_batch(b)), b)
  File "/usr/local/lib/python3.6/dist-packages/fastai2/data/load.py", line 126, in create_batch
    def create_batch(self, b): return (fa_collate,fa_convert)[self.prebatched](b)
  File "/usr/local/lib/python3.6/dist-packages/fastai2/data/load.py", line 46, in fa_collate
    else type(t[0])([fa_collate(s) for s in zip(*t)]) if isinstance(b, Sequence)
  File "/usr/local/lib/python3.6/dist-packages/fastai2/data/load.py", line 46, in <listcomp>
    else type(t[0])([fa_collate(s) for s in zip(*t)]) if isinstance(b, Sequence)
  File "/usr/local/lib/python3.6/dist-packages/fastai2/data/load.py", line 45, in fa_collate
    return (default_collate(t) if isinstance(b, _collate_types)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 480 and 320 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
```

**Comment by sgugger** [comment]
Please refer to the [updated script](https://github.com/fastai/fastai2/blob/f22423e3f5075d7c5db26e7338f9359b64150323/nbs/examples/train_imagenette.py#L14) in the examples folder, `item_tfms` and `batch_tfms` should be passed to the datablock now.

Also please use the [forum](https://forums.fast.ai/) for debugging your code, we keep issues for bugs inside the library only.
