### ISSUE TITLE
NameError: name 'log_args' is not defined

### ISSUE THREAD

**Issue by cpoptic** [fastai/fastai2#270]
`from fastai2.tabular.all import *`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\projects\fastai\fastai2\fastai2\tabular\all.py", line 1, in <module>
    from ..basics import *
  File "D:\projects\fastai\fastai2\fastai2\basics.py", line 1, in <module>
    from .data.all import *
  File "D:\projects\fastai\fastai2\fastai2\data\all.py", line 2, in <module>
    from .core import *
  File "D:\projects\fastai\fastai2\fastai2\data\core.py", line 8, in <module>
    from .load import *
  File "D:\projects\fastai\fastai2\fastai2\data\load.py", line 59, in <module>
    @log_args(but='dataset,wif,create_batch,create_batches,create_item,retain,get_idxs,sample,shuffle_fn,do_batch')
NameError: name 'log_args' is not defined

**Comment by borisdayma** [comment]
You need latest version (git) of `fastcore`

**Comment by sgugger** [comment]
Yes, and please search closed issues before opening a new one since you could see the answer there :)
