### ISSUE TITLE
AttributeError: train_dl in lesson6-rossmann.py

### ISSUE THREAD

**Issue by rraminen** [fastai/fastai2#354]
The below error occurs in lesson6-rossmann.py as there is no attribute 'train_dl' in 'test_dbunch'
```
Traceback (most recent call last):
  File "lesson6-rossmann.py", line 287, in <module>
    tst_preds,_ = learn.get_preds(dl=test_dbunch.train_dl)
  File "/usr/local/lib/python3.6/dist-packages/fastcore/foundation.py", line 234, in __getattr__
    if attr is not None: return getattr(attr,k)
  File "/usr/local/lib/python3.6/dist-packages/fastcore/foundation.py", line 234, in __getattr__
    if attr is not None: return getattr(attr,k)
  File "/usr/local/lib/python3.6/dist-packages/fastcore/foundation.py", line 234, in __getattr__
    if attr is not None: return getattr(attr,k)
  File "/usr/local/lib/python3.6/dist-packages/fastcore/transform.py", line 191, in __getattr__
    def __getattr__(self,k): return gather_attrs(self, k, 'fs')
  File "/usr/local/lib/python3.6/dist-packages/fastcore/transform.py", line 155, in gather_attrs
    if not res: raise AttributeError(k)
AttributeError: train_dl

```

Please suggest the fix

**Comment by muellerzr** [comment]
It should just be .train, not .train_dl. Something that wasn’t quite updated.

**Comment by sgugger** [comment]
Should be fixed now.
