### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float128'

### ISSUE THREAD

**Issue by nickcorona** [fastai/fastai2#387]
This only occurs on Windows. It's because windows python doesn't have float128. I would suggest using np.longdouble instead.

```Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MSC v.1916 64 bit (AMD64)] onn win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from fastai2.tabular.all import *
>>> path = untar_data(URLs.ADULT_SAMPLE)
>>> df = pd.read_csv(path / "adult.csv")
>>> valid_idx = range(len(df) - 2000, len(df))
>>> df.head()
   age          workclass  fnlwgt     education  ...  capital-loss hours-per-week  native-country salary
0   49            Private  101320    Assoc-acdm  ...          1902             40   United-States  >=50k
1   44            Private  236746       Masters  ...             0             45   United-States  >=50k
2   38            Private   96185       HS-grad  ...             0             32   United-States   <50k
3   38       Self-emp-inc  112847   Prof-school  ...             0             40   United-States  >=50k
4   42   Self-emp-not-inc   82297       7th-8th  ...             0             50   United-States   <50k

[5 rows x 15 columns]
>>> cat_names = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']
>>> dep_var = 'salary'
>>> procs = [FillMissing, Categorify]
>>> data = TabularPandas(df, procs=procs, cat_names=cat_names, y_names='salary')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\nickl\fastai2\fastai2\tabular\core.py", line 145, in __init__
    if reduce_memory: df = df_shrink(df)
  File "c:\users\nickl\fastai2\fastai2\tabular\core.py", line 121, in df_shrink
    dt = df_shrink_dtypes(df, skip, obj2cat=obj2cat, int2uint=int2uint)
  File "c:\users\nickl\fastai2\fastai2\tabular\core.py", line 99, in df_shrink_dtypes
    'float' : [(np.dtype(x), np.finfo(x).min, np.finfo(x).max) for x in (np.float32, np.float64, np.float128)],}
  File "C:\Users\nickl\miniconda3\lib\site-packages\numpy\__init__.py", line 220, in __getattr__       
    "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'float128'
```

**Comment by muellerzr** [comment]
A PR would be welcome, as that seems a very acceptable solution. From what I've found float128 actually can have different precisions based on the OS used too. Let me know if you run into any troubles (otherwise I can go ahead and do one 😄 )

**Comment by jph00** [comment]
OK will make that change - thanks for letting us know.
