### ISSUE TITLE
failed nbdev_build_lib, FileNotFoundError topnav.yml

### ISSUE THREAD

**Issue by richarddwang** [fastai/fastai2#463]
Steps
```
# Fork
~ % git clone https://github.com/richarddwang/fastai2.git
~ % cd fastai2
~/fastai2 % pip install -e ".[dev]"
~/fastai2 % nbdev_install_git_hooks
~/fasati2 % nbdev_build_lib
```
Error Message
```
Traceback (most recent call last):
  File "/home/yisiang/miniconda3/envs/pr/bin/nbdev_build_lib", line 8, in <module>
    sys.exit(nbdev_build_lib())
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/site-packages/fastscript/core.py", line 76, in _f
    func(**args.__dict__)
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/site-packages/nbdev/cli.py", line 138, in nbdev_build_lib
    write_tmpls()
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/site-packages/nbdev/export2html.py", line 501, in write_tmpls
    write_tmpl(topnav_tmpl, 'host git_url', cfg, cfg.doc_path/'_data'/'topnav.yml')
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/site-packages/nbdev/export2html.py", line 494, in write_tmpl
    dest.write_text(outp)
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/pathlib.py", line 1235, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
  File "/home/yisiang/miniconda3/envs/pr/lib/python3.7/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/yisiang/fastai2/docs/_data/topnav.yml'
```

**Comment by KushajveerSingh** [comment]
`docs` has been moved to a new repo. Use `git clone --recurse-submodules https://github.com/fastai/fastai2` to clone fastai.
